[package]
name = "xtask"
version = "0.1.0"
edition = "2021"

[dependencies]
kv = { path = "../kv" }
anyhow = "1.0.86"
clap = { version = "4.5.9", features = ["derive", "string"] }
clap_mangen = "0.2.22"
