name: Install Nix
description: Reusable action that executes all the necessary steps to install Nix
runs:
  using: composite
  steps:
    - name: Install Nix
      uses: nixbuild/nix-quick-install-action@v28

    - name: Cache Nix store
      uses: nix-community/cache-nix-action@v5
      with:
        primary-key: ${{ github.job }}-${{ runner.os }}-${{ hashFiles('**/*.nix') }}
        restore-prefixes-first-match: ${{ github.job }}-${{ runner.os }}-
        save-always: true
