name: CI

on:
  push:
    branches: ["**"]

defaults:
  run:
    shell: bash -c "nix develop --impure -c bash -e {0}"

jobs:
  build:
    name: Build

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, macos-13]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: ./.github/actions/nix

      - name: Build
        run: nix build

  test:
    name: Test

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, macos-13]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: ./.github/actions/nix

      - name: Test
        run: cargo test

  clippy:
    name: Clippy

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: ./.github/actions/nix

      - name: Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

  generate:
    name: Generate

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: ./.github/actions/nix

      - name: Generate Entities
        run: cargo run --package entity

      - name: Verify
        run: test -z "$(git status --porcelain)"
