name: CI

on:
  push:
    branches: ["**"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: ./.github/actions/nix

      - name: Build
        run: nix build
