name: CI

on:
  push:
    branches: ["**"]

defaults:
  run:
    shell: bash -c "nix develop --impure -c bash -e {0}"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: ./.github/actions/nix

      - name: Build
        run: nix build

  test:
    name: Test

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: ./.github/actions/nix

      - name: Test
        run: cargo test

  check:
    name: Check

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: ./.github/actions/nix

      - name: Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
